package tools

// Language learning tools — both programming and written/spoken languages.
//
// Sessions are stored in CLAUDE_DIR/learning/<language>/<session-id>.json
// Each session tracks: language, mode (vocab|grammar|code_challenge|conversation),
// current lesson, history of exchanges, and score.
//
// Tools:
//   learn_start    — start or resume a learning session
//   learn_exercise — get the next exercise/challenge for the active session
//   learn_submit   — submit an answer and get feedback + score
//   learn_status   — show progress across all languages
//   learn_schedule — show/set a learning schedule (stored in CLAUDE_DIR/learning/schedule.json)
//
// The exercises themselves are generated by Claude via the session context
// (the tool provides scaffolding; actual exercise generation happens in the AI conversation).

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/caboose-mcp/server/config"
	"github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
)

type LearningSession struct {
	ID           string     `json:"id"`
	Language     string     `json:"language"`      // "python", "rust", "japanese", "spanish", etc.
	LanguageType string     `json:"language_type"` // "programming" or "spoken"
	Mode         string     `json:"mode"`          // vocab | grammar | code_challenge | conversation | quiz
	Level        string     `json:"level"`         // beginner | intermediate | advanced
	StartedAt    time.Time  `json:"started_at"`
	LastActive   time.Time  `json:"last_active"`
	Score        int        `json:"score"`
	TotalAsked   int        `json:"total_asked"`
	History      []Exchange `json:"history"`
}

type Exchange struct {
	At       time.Time `json:"at"`
	Prompt   string    `json:"prompt"`
	Answer   string    `json:"answer"`
	Correct  bool      `json:"correct"`
	Feedback string    `json:"feedback"`
}

type LearningSchedule struct {
	DailyLanguages []ScheduleEntry `json:"daily_languages"`
	Reminders      []string        `json:"reminders"` // cron expressions
}

type ScheduleEntry struct {
	Language string `json:"language"`
	Mode     string `json:"mode"`
	Duration int    `json:"duration_minutes"`
}

func RegisterLearning(s *server.MCPServer, cfg *config.Config) {
	s.AddTool(mcp.NewTool("learn_start",
		mcp.WithDescription("Start or resume a language learning session. Returns session context for the AI to use when generating exercises."),
		mcp.WithString("language", mcp.Required(), mcp.Description("Language to learn (e.g. python, rust, japanese, spanish, french)")),
		mcp.WithString("mode", mcp.Description("Learning mode: vocab | grammar | code_challenge | conversation | quiz (default: code_challenge for programming, vocab for spoken)")),
		mcp.WithString("level", mcp.Description("Level: beginner | intermediate | advanced (default: beginner)")),
	), learnStartHandler(cfg))

	s.AddTool(mcp.NewTool("learn_exercise",
		mcp.WithDescription("Get context for the next exercise in an active session. Returns session state so the AI can generate the next appropriate challenge."),
		mcp.WithString("session_id", mcp.Required(), mcp.Description("Session ID from learn_start")),
	), learnExerciseHandler(cfg))

	s.AddTool(mcp.NewTool("learn_submit",
		mcp.WithDescription("Record an answer and feedback for the current exercise."),
		mcp.WithString("session_id", mcp.Required(), mcp.Description("Session ID")),
		mcp.WithString("prompt", mcp.Required(), mcp.Description("The exercise/question that was asked")),
		mcp.WithString("answer", mcp.Required(), mcp.Description("The learner's answer")),
		mcp.WithBoolean("correct", mcp.Required(), mcp.Description("Whether the answer was correct")),
		mcp.WithString("feedback", mcp.Description("Feedback or explanation to record")),
	), learnSubmitHandler(cfg))

	s.AddTool(mcp.NewTool("learn_status",
		mcp.WithDescription("Show learning progress across all languages."),
	), learnStatusHandler(cfg))

	s.AddTool(mcp.NewTool("learn_schedule",
		mcp.WithDescription("View or update the daily learning schedule."),
		mcp.WithBoolean("update", mcp.Description("If true, update the schedule with the provided entries")),
		mcp.WithString("schedule_json", mcp.Description("JSON schedule to save (array of {language, mode, duration_minutes})")),
	), learnScheduleHandler(cfg))
}

func learningDir(cfg *config.Config, language string) string {
	return filepath.Join(cfg.ClaudeDir, "learning", language)
}

func classifyLanguage(lang string) string {
	programming := map[string]bool{
		"python": true, "go": true, "golang": true, "rust": true, "javascript": true,
		"typescript": true, "java": true, "c": true, "cpp": true, "c++": true,
		"ruby": true, "php": true, "swift": true, "kotlin": true, "scala": true,
		"haskell": true, "elixir": true, "clojure": true, "r": true, "sql": true,
		"bash": true, "shell": true, "lua": true,
	}
	if programming[strings.ToLower(lang)] {
		return "programming"
	}
	return "spoken"
}

func defaultMode(langType string) string {
	if langType == "programming" {
		return "code_challenge"
	}
	return "vocab"
}

func learnStartHandler(cfg *config.Config) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(_ context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		language, err := req.RequireString("language")
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		language = strings.ToLower(language)
		langType := classifyLanguage(language)
		mode := req.GetString("mode", defaultMode(langType))
		level := req.GetString("level", "beginner")

		dir := learningDir(cfg, language)
		if err := os.MkdirAll(dir, 0755); err != nil {
			return mcp.NewToolResultError(fmt.Sprintf("mkdir: %v", err)), nil
		}

		// Check for an existing active session
		entries, _ := os.ReadDir(dir)
		for _, e := range entries {
			if !strings.HasSuffix(e.Name(), ".json") || e.Name() == "schedule.json" {
				continue
			}
			data, err := os.ReadFile(filepath.Join(dir, e.Name()))
			if err != nil {
				continue
			}
			var s LearningSession
			if err := json.Unmarshal(data, &s); err != nil {
				continue
			}
			// Resume if same language and mode, active within 24h
			if s.Mode == mode && time.Since(s.LastActive) < 24*time.Hour {
				s.LastActive = time.Now()
				data, _ = json.MarshalIndent(s, "", "  ")
				os.WriteFile(filepath.Join(dir, s.ID+".json"), data, 0644)
				out, _ := json.MarshalIndent(s, "", "  ")
				return mcp.NewToolResultText(fmt.Sprintf("Resumed session %s for %s (%s mode, %s level)\n\nSession state:\n%s", s.ID, language, mode, s.Level, out)), nil
			}
		}

		// Create new session
		id := fmt.Sprintf("%d", time.Now().UnixNano())
		s := LearningSession{
			ID:           id,
			Language:     language,
			LanguageType: langType,
			Mode:         mode,
			Level:        level,
			StartedAt:    time.Now(),
			LastActive:   time.Now(),
			Score:        0,
			TotalAsked:   0,
			History:      []Exchange{},
		}
		data, _ := json.MarshalIndent(s, "", "  ")
		if err := os.WriteFile(filepath.Join(dir, id+".json"), data, 0644); err != nil {
			return mcp.NewToolResultError(fmt.Sprintf("save: %v", err)), nil
		}

		instructions := generateLearningInstructions(s)
		return mcp.NewToolResultText(fmt.Sprintf("Started session %s\n\n%s\n\nSession state:\n%s", id, instructions, data)), nil
	}
}

func generateLearningInstructions(s LearningSession) string {
	switch s.LanguageType {
	case "programming":
		return fmt.Sprintf(`Learning %s — %s mode (%s level)

Instructions for AI: Generate %s exercises appropriate for a %s-level %s developer.
- For code_challenge: provide a coding problem with expected input/output
- For quiz: ask multiple-choice questions about language features
- Track score and adjust difficulty based on performance
- After each answer, explain the concept even if correct`, s.Language, s.Mode, s.Level, s.Mode, s.Level, s.Language)
	default:
		return fmt.Sprintf(`Learning %s — %s mode (%s level)

Instructions for AI: Generate %s exercises for a %s-level %s learner.
- For vocab: present a word/phrase, ask for translation or usage
- For grammar: show a sentence with blanks or errors to correct
- For conversation: simulate a real-world dialogue scenario
- Include pronunciation hints where helpful
- Keep track of score and adjust difficulty`, s.Language, s.Mode, s.Level, s.Mode, s.Level, s.Language)
	}
}

func learnExerciseHandler(cfg *config.Config) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(_ context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		sessionID, err := req.RequireString("session_id")
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		// Find session across all language dirs
		s, dir, err := findSession(cfg, sessionID)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		// Return session context for AI to generate exercise
		recentHistory := s.History
		if len(recentHistory) > 5 {
			recentHistory = recentHistory[len(recentHistory)-5:]
		}
		recent, _ := json.MarshalIndent(recentHistory, "", "  ")

		summary := fmt.Sprintf(`Session: %s
Language: %s (%s)
Mode: %s | Level: %s
Progress: %d/%d correct (score: %d)
Recent exchanges: %s

Generate the next exercise based on the above context.
%s`, s.ID, s.Language, s.LanguageType, s.Mode, s.Level,
			s.Score, s.TotalAsked, s.Score, recent,
			generateLearningInstructions(s))

		_ = dir
		return mcp.NewToolResultText(summary), nil
	}
}

func learnSubmitHandler(cfg *config.Config) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(_ context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		sessionID, err := req.RequireString("session_id")
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		prompt, err := req.RequireString("prompt")
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		answer, err := req.RequireString("answer")
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		correct, err := req.RequireBool("correct")
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		feedback := req.GetString("feedback", "")

		s, dir, err := findSession(cfg, sessionID)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		s.TotalAsked++
		if correct {
			s.Score++
		}
		s.LastActive = time.Now()
		s.History = append(s.History, Exchange{
			At:       time.Now(),
			Prompt:   prompt,
			Answer:   answer,
			Correct:  correct,
			Feedback: feedback,
		})
		// Keep history bounded to last 50 exchanges
		if len(s.History) > 50 {
			s.History = s.History[len(s.History)-50:]
		}

		data, _ := json.MarshalIndent(s, "", "  ")
		os.WriteFile(filepath.Join(dir, s.ID+".json"), data, 0644)

		pct := 0
		if s.TotalAsked > 0 {
			pct = (s.Score * 100) / s.TotalAsked
		}
		result := "incorrect"
		if correct {
			result = "correct"
		}
		return mcp.NewToolResultText(fmt.Sprintf("Recorded: %s\nScore: %d/%d (%d%%)\nFeedback: %s",
			result, s.Score, s.TotalAsked, pct, feedback)), nil
	}
}

func learnStatusHandler(cfg *config.Config) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(_ context.Context, _ mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		baseDir := filepath.Join(cfg.ClaudeDir, "learning")
		entries, err := os.ReadDir(baseDir)
		if err != nil {
			if os.IsNotExist(err) {
				return mcp.NewToolResultText("(no learning sessions yet — use learn_start to begin)"), nil
			}
			return mcp.NewToolResultError(fmt.Sprintf("readdir: %v", err)), nil
		}

		var lines []string
		lines = append(lines, "Learning Progress:")
		for _, e := range entries {
			if !e.IsDir() {
				continue
			}
			lang := e.Name()
			sessions, _ := os.ReadDir(filepath.Join(baseDir, lang))
			for _, sf := range sessions {
				if !strings.HasSuffix(sf.Name(), ".json") {
					continue
				}
				data, _ := os.ReadFile(filepath.Join(baseDir, lang, sf.Name()))
				var s LearningSession
				if json.Unmarshal(data, &s) != nil {
					continue
				}
				pct := 0
				if s.TotalAsked > 0 {
					pct = (s.Score * 100) / s.TotalAsked
				}
				lines = append(lines, fmt.Sprintf("  %s (%s, %s): %d/%d correct (%d%%) — last active: %s",
					s.Language, s.Mode, s.Level, s.Score, s.TotalAsked, pct,
					s.LastActive.Format("2006-01-02 15:04")))
			}
		}
		if len(lines) == 1 {
			return mcp.NewToolResultText("(no learning sessions yet — use learn_start to begin)"), nil
		}
		return mcp.NewToolResultText(strings.Join(lines, "\n")), nil
	}
}

func learnScheduleHandler(cfg *config.Config) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(_ context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		schedulePath := filepath.Join(cfg.ClaudeDir, "learning", "schedule.json")

		if req.GetBool("update", false) {
			schedJSON := req.GetString("schedule_json", "")
			if schedJSON == "" {
				return mcp.NewToolResultError("schedule_json is required when update=true"), nil
			}
			var entries []ScheduleEntry
			if err := json.Unmarshal([]byte(schedJSON), &entries); err != nil {
				return mcp.NewToolResultError(fmt.Sprintf("invalid JSON: %v", err)), nil
			}
			sched := LearningSchedule{DailyLanguages: entries}
			data, _ := json.MarshalIndent(sched, "", "  ")
			os.MkdirAll(filepath.Dir(schedulePath), 0755)
			if err := os.WriteFile(schedulePath, data, 0644); err != nil {
				return mcp.NewToolResultError(fmt.Sprintf("save: %v", err)), nil
			}
			return mcp.NewToolResultText("schedule updated"), nil
		}

		data, err := os.ReadFile(schedulePath)
		if err != nil {
			return mcp.NewToolResultText("(no schedule set — use learn_schedule with update=true and schedule_json)"), nil
		}
		return mcp.NewToolResultText(string(data)), nil
	}
}

func findSession(cfg *config.Config, sessionID string) (LearningSession, string, error) {
	baseDir := filepath.Join(cfg.ClaudeDir, "learning")
	langDirs, err := os.ReadDir(baseDir)
	if err != nil {
		return LearningSession{}, "", fmt.Errorf("no learning sessions found")
	}
	for _, d := range langDirs {
		if !d.IsDir() {
			continue
		}
		path := filepath.Join(baseDir, d.Name(), sessionID+".json")
		data, err := os.ReadFile(path)
		if err != nil {
			continue
		}
		var s LearningSession
		if err := json.Unmarshal(data, &s); err != nil {
			continue
		}
		return s, filepath.Join(baseDir, d.Name()), nil
	}
	return LearningSession{}, "", fmt.Errorf("session %q not found", sessionID)
}
