import { Clock, GitCommit, Tag, ExternalLink } from 'lucide-react'

// This data is auto-generated by CI — see .github/workflows/ci.yml (generate-changelog job).
// In dev/placeholder mode it shows a static example.
// At build time, CI writes src/data/changelog.json via `git log`.
let changelogData: ChangelogEntry[]
try {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  changelogData = require('../data/changelog.json') as ChangelogEntry[]
} catch {
  changelogData = PLACEHOLDER_CHANGELOG
}

export type ChangelogEntry = {
  hash: string
  date: string
  subject: string
  author: string
  tags: string[]
}

export default function Changelog() {
  const entries = changelogData

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 py-8 animate-fade-in">
      <div className="mb-8">
        <div className="flex items-center gap-2 mb-1">
          <Clock className="w-5 h-5 text-accent-green" />
          <h1 className="text-2xl font-bold text-text-primary">Changelog</h1>
        </div>
        <p className="text-sm text-text-secondary">
          Auto-generated from git history on every deploy. Each entry links to the GitHub commit.
        </p>
      </div>

      <div className="relative">
        {/* Timeline line */}
        <div className="absolute left-4 top-0 bottom-0 w-px bg-border" />

        <div className="space-y-0">
          {entries.map((entry, i) => (
            <div key={entry.hash} className="relative pl-10 pb-6 animate-slide-up"
              style={{ animationDelay: `${i * 30}ms` }}>
              {/* Dot */}
              <div className={`absolute left-3 top-1.5 w-2 h-2 rounded-full border
                              ${entry.tags.includes('feat') ? 'bg-accent-green border-accent-green/50'
                                : entry.tags.includes('fix') ? 'bg-accent-blue border-accent-blue/50'
                                : 'bg-border-bright border-border'}`}
              />

              <div className="group">
                <div className="flex flex-wrap items-start gap-2 mb-1">
                  {/* Type badge */}
                  {entry.tags.map(tag => (
                    <span key={tag} className={`tag text-[10px] border ${
                      tag === 'feat' ? 'text-accent-green bg-accent-green/10 border-accent-green/20'
                      : tag === 'fix' ? 'text-accent-blue bg-accent-blue/10 border-accent-blue/20'
                      : tag === 'docs' ? 'text-accent-purple bg-accent-purple/10 border-accent-purple/20'
                      : tag === 'ci' ? 'text-accent-orange bg-accent-orange/10 border-accent-orange/20'
                      : 'text-text-muted bg-bg border-border'
                    }`}>
                      {tag}
                    </span>
                  ))}

                  {/* Commit link */}
                  <a
                    href={`https://github.com/cxm6467/caboose-mcp/commit/${entry.hash}`}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="flex items-center gap-1 text-xs text-text-muted hover:text-text-secondary
                               transition-colors ml-auto"
                  >
                    <GitCommit className="w-3 h-3" />
                    <code className="font-mono">{entry.hash.slice(0, 7)}</code>
                    <ExternalLink className="w-2.5 h-2.5" />
                  </a>
                </div>

                <p className="text-sm text-text-primary leading-snug">{entry.subject}</p>
                <p className="text-xs text-text-muted mt-1">
                  {new Date(entry.date).toLocaleDateString('en-US', {
                    year: 'numeric', month: 'long', day: 'numeric'
                  })}{' '}
                  · {entry.author}
                </p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}

const PLACEHOLDER_CHANGELOG: ChangelogEntry[] = [
  {
    hash: '57c55de',
    date: '2026-03-19',
    subject: 'feat: JWT RBAC magic link auth + identity linking',
    author: 'Chris Marasco',
    tags: ['feat'],
  },
  {
    hash: '4f6a33f',
    date: '2026-03-18',
    subject: 'feat: split tools into hosted/local/combined tiers',
    author: 'Chris Marasco',
    tags: ['feat'],
  },
  {
    hash: 'da61b69',
    date: '2026-03-10',
    subject: 'feat: complete Bruno collection — 120 requests across 24 categories',
    author: 'Chris Marasco',
    tags: ['feat', 'docs'],
  },
  {
    hash: 'a3c1b9f',
    date: '2026-03-05',
    subject: 'feat: calendar.go — per-JTI Google token + scope checks',
    author: 'Chris Marasco',
    tags: ['feat'],
  },
  {
    hash: '9e4d721',
    date: '2026-02-28',
    subject: 'ci: add golangci-lint, unit tests, coverage gate, e2e smoke',
    author: 'Chris Marasco',
    tags: ['ci'],
  },
  {
    hash: '3f8a451',
    date: '2026-02-20',
    subject: 'feat: notes.go — Google Drive backup/restore',
    author: 'Chris Marasco',
    tags: ['feat'],
  },
  {
    hash: '1d5c982',
    date: '2026-02-15',
    subject: 'fix: bot_agent.go — inject identity claims for Discord SSO',
    author: 'Chris Marasco',
    tags: ['fix'],
  },
  {
    hash: 'c7b3f16',
    date: '2026-02-10',
    subject: 'docs: setup.md — AWS cost estimates and JWT RBAC section',
    author: 'Chris Marasco',
    tags: ['docs'],
  },
]
